export type appScreen =
  | 'ProfileScreen'
  | 'SearchModal'
  | 'RegisterScreen'
  | 'SplashScreen'
  | 'OverViewScreen'
  | 'InvestMentScreen'
  | 'ManageScreen'
  | 'ProductDetailsModal'
  | 'Alert'
  | 'LoginScreen'
  | 'OtpRequestModal'
  | 'ForgotPasswordScreen'
  | 'SetPasswordScreen'
  | 'RegisterScreen';
